---
roles:
  - name: jnv.unattended-upgrades
    version: v1.11.0

  - name: geerlingguy.mysql
    version: 3.3.2

  - name: geerlingguy.certbot
    version: 4.2.0

collections:
  - community.mysql
  